export const TRIGGER_GAP_MS=4*60*60*1000
export const TBQ_PENALTY_MINUTES=2
export const REPORT_PENALTY_MINUTES=5
export const FINAL_QUEST_CANDIDATE_MIN=10
export const FINAL_QUEST_CANDIDATE_MAX=15
export const JWT_EXPIRY_SECONDS=4*24*60*60
export const COOKIE_NAME='suffer_session'

export const FIXED_GROUP_SIZE=4
export const REPORT_APPROVAL_THRESHOLD=FIXED_GROUP_SIZE-1
export const MINUTE_MS=60_000
export const FACE_SERVICE_TIMEOUT_MS=7_000
export const FACE_ENROLL_TIMEOUT_MS=20_000
export const SSE_POLL_INTERVAL_MS=2_000
export const PHOTO_JOB_TIMEOUT_MS=2*MINUTE_MS
